<?php

use DI\Container;
use App\Repositories\Contracts\CartRepositoryInterface;
use App\Repositories\Contracts\UserRepositoryInterface;
use App\Repositories\Contracts\ProductRepositoryInterface;
use App\Repositories\CartRepository;
use App\Repositories\CategoryRepository;
use App\Repositories\Contracts\CategoryRepositoryInterface;
use App\Repositories\Contracts\RoleRepositoryInterface;
use App\Repositories\Contracts\UserRoleRepositoryInterface;
use App\Repositories\UserRepository;
use App\Repositories\ProductRepository;
use App\Repositories\RoleRepository;
use App\Repositories\UserRoleRepository;
use App\Services\CartService;
use App\Services\UserRoleService;
use App\Services\UserService;
use App\Services\StripeService;
use Slim\Views\PhpRenderer;
use Stripe\StripeClient;
use App\Config\Env;
use App\Repositories\Contracts\EmailChangeRepositoryInterface;
use App\Repositories\Contracts\PasswordRepositoryInterface;
use App\Repositories\Contracts\ProductImageRepositoryInterface;
use App\Repositories\Contracts\ProductInformationRepositoryInterface;
use App\Repositories\Contracts\ReviewRepositoryInterface;
use App\Repositories\Contracts\SaleItemRepositoryInterface;
use App\Repositories\Contracts\SaleRepositoryInterface;
use App\Repositories\Contracts\ShipmentRepositoryInterface;
use App\Repositories\Contracts\ShippingAddressRepositoryInterface;
use App\Repositories\EmailChangeRepository;
use App\Repositories\PasswordResetRepository;
use App\Repositories\ProductImageRepository;
use App\Repositories\ProductInformationRepository;
use App\Repositories\ReviewRepository;
use App\Repositories\SaleItemRepository;
use App\Repositories\SaleRepository;
use App\Repositories\ShipmentRepository;
use App\Repositories\ShippingAddressRepository;
use App\Services\CategoryService;
use App\Services\EmailChangeService;
use App\Services\MailService;
use App\Services\PasswordResetService;
use App\Services\ProductImageService;
use App\Services\ProductInformationService;
use App\Services\ProductService;
use App\Services\ReviewService;
use App\Services\SaleItemService;
use App\Services\SaleService;
use App\Services\ShipmentService;
use App\Services\ShippingAddressService;
use App\Services\ShippoService;
use Rakit\Validation\Validator;

$container = new Container();

$container->set(CartRepositoryInterface::class, DI\autowire(CartRepository::class));
$container->set(UserRepositoryInterface::class, DI\autowire(UserRepository::class));
$container->set(ProductRepositoryInterface::class, DI\autowire(ProductRepository::class));
$container->set(UserService::class, DI\autowire());
$container->set(UserRoleService::class, DI\autowire());
$container->set(CategoryRepositoryInterface::class, DI\autowire(CategoryRepository::class));
$container->set(PhpRenderer::class, function () {
    return new PhpRenderer(__DIR__ . '/views/');
});
$container->set(RoleRepositoryInterface::class, DI\autowire(RoleRepository::class));
$container->set(UserRoleRepositoryInterface::class, DI\autowire(UserRoleRepository::class));
$container->set(UserRoleService::class, DI\autowire());
$container->set(CartService::class, DI\autowire());
$container->set(CategoryService::class, Di\autowire());
$container->set(ProductService::class, Di\autowire());
$container->set(ReviewRepositoryInterface::class, Di\autowire(ReviewRepository::class));
$container->set(ReviewService::class, Di\autowire());
$container->set(ProductImageRepositoryInterface::class, Di\autowire(ProductImageRepository::class));
$container->set(ProductImageService::class, Di\autowire());
$container->set(ProductInformationRepositoryInterface::class, Di\autowire(ProductInformationRepository::class));
$container->set(ProductInformationService::class, Di\autowire());
$container->set(SaleRepositoryInterface::class, Di\autowire(SaleRepository::class));
$container->set(SaleItemRepositoryInterface::class, Di\autowire(SaleItemRepository::class));
$container->set(SaleItemService::class, Di\autowire());
$container->set(SaleService::class, Di\autowire());
$container->set(MailService::class, Di\autowire());
$container->set(StripeClient::class, function () {
    return new StripeClient(Env::get("STRIPE_SECRET"));
});
$container->set(StripeService::class,  DI\autowire());
$container->set(ShippingAddressRepositoryInterface::class, Di\autowire(ShippingAddressRepository::class));
$container->set(ShippingAddressService::class, Di\autowire());
$container->set(Validator::class,  DI\autowire());
$container->set(PasswordRepositoryInterface::class, Di\autowire(PasswordResetRepository::class));
$container->set(PasswordResetService::class, Di\autowire());
$container->set(EmailChangeRepositoryInterface::class, Di\autowire(EmailChangeRepository::class));
$container->set(EmailChangeService::class, Di\autowire());
$container->set(ShippoService::class, function () {
    return new ShippoService(Env::get("SHIPPO_SECRET"));
});
$container->set(ShipmentRepositoryInterface::class, Di\autowire(ShipmentRepository::class));
$container->set(ShipmentService::class, Di\autowire());
return $container;
